baseURL = "https://blog.paul.land/"
languageCode = "en-us"
title = "paul land"
copyright = "paul william keller savides"
theme = "harbor"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
  post = "/:year/:month/:day/:slug/"
  page = "/:filename/"

[outputs]
  section = ["JSON", "HTML"]

[params]
  mainSections = ["post"]

[params.logo]
  url = "icon.jpg"
  width = 50
  height = 50
  alt = "Logo"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "twitter"
  url="https://twitter.com/paulsavides"
  icon="fab fa-twitter"

[[params.social]]
  name= "twitter"
  url="https://github.com/paulsavides"
  icon="fab fa-github"


