name: trigger-azure-pipelines-run
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    - .editorconfig
    - .gitignore
  workflow_dispatch:
jobs:
  trigger-azure-pipelines-run:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Azure Pipelines Build & Publish
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: https://dev.azure.com/paulsavides/paulsavides.com
        azure-pipeline-name: StaticSites - blog.paul.land
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
